title: Skill-based Recommendation System for Green Jobs
description: This website provides supporting materials for the green skill-based recommendation system.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

